# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: '**'

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # https://nodejs.org/en/about/releases/
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      - name: install
        run: yarn --immutable
      - name: run eslint
        run: yarn lint:js
      - name: run stylelint
        run: yarn lint:css

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # https://nodejs.org/en/about/releases/
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
      - name: install
        run: yarn --immutable
      - name: run tests
        run: yarn test
